/**
 * DCSA OpenAPI specification for Booking
 * API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the [Information Model 2022.Q4](https://dcsa.org/wp-content/uploads/2022/12/DCSA_Information-Model-2022.Q4-final.pdf). **Please be aware that version 2022.Q4 of the Information Model includes Reefers - this API does not include Reefers.** This API does not define the business rules regarding what is allowed to update at what time. For this the [Interface Standard for the Booking Process 1.0                                                        ](https://dcsa.org/wp-content/uploads/2022/12/12-23-2022-DCSA_Interface_Standard_Booking_v1.0.pdf) should be consulted.  All other documents related to the Booking publication can be found [here](https://knowledge.dcsa.org/s/publication?publicationId=a0r7T000000L8mmQAC)  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the [DCSA Documentation Event Hub](https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB) in order to use the push model. Here events are pushed as they occur.  For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/bkg/v1#v100B3). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The status of the booking. Possible values are: - RECE (Received) - PENU (Pending Update) - PENC (Pending Confirmation) - CONF (Confirmed) - REJE (Rejected) - CANC (Cancelled) - CMPL (Completed)  More details can be found on <a href=\"https://github.com/dcsaorg/DCSA-Information-Model/blob/master/datamodel/referencedata.d/shipmenteventtypecodes.csv\">GitHub</a>. Be aware that the list linked to is the `ShipmentEventTypeCodes` which is equivalent to `documentStatus`, the list is a subset of the possible values.
 */
export type BookingDocumentStatus = 'RECE' | 'PENU' | 'PENC' | 'CONF' | 'REJE' | 'CANC' | 'CMPL';

export const BookingDocumentStatus = {
    RECE: 'RECE' as BookingDocumentStatus,
    PENU: 'PENU' as BookingDocumentStatus,
    PENC: 'PENC' as BookingDocumentStatus,
    CONF: 'CONF' as BookingDocumentStatus,
    REJE: 'REJE' as BookingDocumentStatus,
    CANC: 'CANC' as BookingDocumentStatus,
    CMPL: 'CMPL' as BookingDocumentStatus
};
