/**
 * DCSA OpenAPI specification for Booking v2 - Beta 1
 * API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the *** [Information Model v2022.1]() *** Will be updated soon ***. This API does not define the business rules regarding what is allowed to update at what time. For this the [BKG IFS]() *** Will be updated soon *** should be consulted.  All other documents related to the Booking publication can be found [here](https://knowledge.dcsa.org/s/publication?publicationId=a0r7T000000L8mmQAC)  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the [DCSA Documentation Event Hub](https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB) in order to use the push model. Here events are pushed as they occur.  For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/bkg/v1#v200B1). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments. 
 *
 * OpenAPI spec version: 2.0.0-Beta-1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookingChannelReference } from './bookingChannelReference';
import { BookingDeep } from './bookingDeep';
import { BookingSummary } from './bookingSummary';
import { Commodity } from './commodity';
import { CommunicationChannelCode } from './communicationChannelCode';
import { ContractQuotationReference } from './contractQuotationReference';
import { CustomsFilingSystem } from './customsFilingSystem';
import { DocumentParty } from './documentParty';
import { ExpectedArrivalAtPlaceOfDeliveryEndDate } from './expectedArrivalAtPlaceOfDeliveryEndDate';
import { ExpectedArrivalAtPlaceOfDeliveryStartDate } from './expectedArrivalAtPlaceOfDeliveryStartDate';
import { ExpectedDepartureDate } from './expectedDepartureDate';
import { ExportDeclarationReference } from './exportDeclarationReference';
import { ImportLicenseReference } from './importLicenseReference';
import { IncoTerms } from './incoTerms';
import { IsAMSACIFilingRequired } from './isAMSACIFilingRequired';
import { IsCustomsFilingSubmissionByShipper } from './isCustomsFilingSubmissionByShipper';
import { IsEquipmentSubstitutionAllowed } from './isEquipmentSubstitutionAllowed';
import { IsExportDeclarationRequired } from './isExportDeclarationRequired';
import { IsImportLicenseRequired } from './isImportLicenseRequired';
import { IsPartialLoadAllowed } from './isPartialLoadAllowed';
import { ModeOfTransport } from './modeOfTransport';
import { PaymentTermCode } from './paymentTermCode';
import { Reference } from './reference';
import { ShipmentLocation } from './shipmentLocation';
import { TransportDocumentTypeCode } from './transportDocumentTypeCode';
import { ValueAddedService } from './valueAddedService';
import { VesselIMONumber } from './vesselIMONumber';

/**
 * includes the information requested in a booking, service terms and types as well as the assigned booking reference by the carrier. 
 */
export interface BookingResponse extends BookingSummary { 
    /**
     * General purpose object to capture `Invoice Payable At` location. The location can be specified in **any** of the following ways: `UN Location Code` and/or an `Address`. 
     */
    invoicePayableAt?: any;
    /**
     * General purpose object to capture `Place of B/L Issue` location. The location can be specified in **any** of the following ways: `UN Location Code` and/or an `Address`.  The location where the original transport document (`Bill of Lading`) will be issued. 
     */
    placeOfBLIssue?: any;
    commodities: Array<Commodity>;
    valueAddedServices?: Array<ValueAddedService>;
    references?: Array<Reference>;
    documentParties?: Array<DocumentParty>;
    shipmentLocations?: Array<ShipmentLocation>;
}