/**
 * DCSA OpenAPI specification for Booking v2 - Beta 1
 * API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the *** [Information Model v2022.1]() *** Will be updated soon ***. This API does not define the business rules regarding what is allowed to update at what time. For this the [BKG IFS]() *** Will be updated soon *** should be consulted.  All other documents related to the Booking publication can be found [here](https://knowledge.dcsa.org/s/publication?publicationId=a0r7T000000L8mmQAC)  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v2/events  in order to poll event information.  It is recomended to implement the [DCSA Documentation Event Hub](https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB) in order to use the push model. Here events are pushed as they occur.  For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/bkg/v2#v200B1). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments. 
 *
 * The version of the OpenAPI document: 2.0.0-Beta-1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DangerousGood } from './dangerousGood';
import { RequestedEquipment } from './requestedEquipment';
import { VolumeUnit } from './volumeUnit';
import { WeightUnit } from './weightUnit';


/**
 * Type of goods in the booking, defined by its commodity type 
 */
export interface Commodity { 
    /**
     * High-level description of goods to be shipped which allow the carrier to confirm acceptance and commercial terms. To be replaced by \"description of goods\" upon submission of shipping instruction 
     */
    commodityType: string;
    /**
     * Used by customs to classify the product being shipped.
     */
    HSCode?: string;
    /**
     * The grand total weight of the cargo and weight per container(s) including packaging items being carried, which can be expressed in imperial or metric terms, as provided by the shipper. Excludes the tare weight of the container(s).\' 
     */
    cargoGrossWeight: number;
    cargoGrossWeightUnit: WeightUnit;
    /**
     * The grand total volume of the commodity 
     */
    cargoGrossVolume?: number;
    cargoGrossVolumeUnit?: VolumeUnit;
    numberOfPackages?: number;
    /**
     * Issue date of the export license applicable to the booking. Mandatory to provide in booking request for specific commodities 
     */
    exportLicenseIssueDate?: string;
    /**
     * Expiry date of the export license applicable to the booking.  Mandatory to provide in booking request for specific commodities. 
     */
    exportLicenseExpiryDate?: string;
    requestedEquipments?: Array<RequestedEquipment>;
    dangerousGoods?: Array<DangerousGood>;
}

