/**
 * DCSA OpenAPI specification for Booking v2 - Beta 1
 * API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the *** [Information Model v2022.1]() *** Will be updated soon ***. This API does not define the business rules regarding what is allowed to update at what time. For this the [BKG IFS]() *** Will be updated soon *** should be consulted.  All other documents related to the Booking publication can be found [here](https://knowledge.dcsa.org/s/publication?publicationId=a0r7T000000L8mmQAC)  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v2/events  in order to poll event information.  It is recomended to implement the [DCSA Documentation Event Hub](https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB) in order to use the push model. Here events are pushed as they occur.  For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/bkg/v2#v200B1). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments. 
 *
 * OpenAPI spec version: 2.0.0-Beta-1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A DCSA provided code for [UN/CEFACT](https://unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred3055.htm) code list providers: - ISO (International Standards Organization) - UNECE (United Nations Economic Commission for Europe) - LLOYD (Lloyd's register of shipping) - BIC (Bureau International des Containeurs) - IMO (International Maritime Organization) - SCAC (Standard Carrier Alpha Code) - ITIGG (International Transport Implementation Guidelines Group) - ITU (International Telecommunication Union) - SMDG (Shipplanning Message Development Group) - EXIS (Exis Technologies Ltd.) - FMC (Federal Maritime Commission) - CBSA (Canada Border Services Agency) - DID (Decentralized Identifier) - LEI (Legal Entity Identifier) - EPI (EBL Platform Identifier) - ZZZ (Mutually defined)  More details can be found on [GitHub](https://github.com/dcsaorg/DCSA-Information-Model/blob/master/datamodel/referencedata.d/codelistresponsibleagencycodes.csv). 
 */
export type DCSAResponsibleAgencyCode = 'ISO' | 'UNECE' | 'LLOYD' | 'BIC' | 'IMO' | 'SCAC' | 'ITIGG' | 'ITU' | 'SMDG' | 'EXIS' | 'FMC' | 'CBSA' | 'DID' | 'LEI' | 'EPI' | 'ZZZ';

export const DCSAResponsibleAgencyCode = {
    ISO: 'ISO' as DCSAResponsibleAgencyCode,
    UNECE: 'UNECE' as DCSAResponsibleAgencyCode,
    LLOYD: 'LLOYD' as DCSAResponsibleAgencyCode,
    BIC: 'BIC' as DCSAResponsibleAgencyCode,
    IMO: 'IMO' as DCSAResponsibleAgencyCode,
    SCAC: 'SCAC' as DCSAResponsibleAgencyCode,
    ITIGG: 'ITIGG' as DCSAResponsibleAgencyCode,
    ITU: 'ITU' as DCSAResponsibleAgencyCode,
    SMDG: 'SMDG' as DCSAResponsibleAgencyCode,
    EXIS: 'EXIS' as DCSAResponsibleAgencyCode,
    FMC: 'FMC' as DCSAResponsibleAgencyCode,
    CBSA: 'CBSA' as DCSAResponsibleAgencyCode,
    DID: 'DID' as DCSAResponsibleAgencyCode,
    LEI: 'LEI' as DCSAResponsibleAgencyCode,
    EPI: 'EPI' as DCSAResponsibleAgencyCode,
    ZZZ: 'ZZZ' as DCSAResponsibleAgencyCode
};