/**
 * DCSA OpenAPI specification for Booking v2 - Beta 1
 * API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the *** [Information Model v2022.1]() *** Will be updated soon ***. This API does not define the business rules regarding what is allowed to update at what time. For this the [BKG IFS]() *** Will be updated soon *** should be consulted.  All other documents related to the Booking publication can be found [here](https://knowledge.dcsa.org/s/publication?publicationId=a0r7T000000L8mmQAC)  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the [DCSA Documentation Event Hub](https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB) in order to use the push model. Here events are pushed as they occur.  For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/bkg/v1#v200B1). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments. 
 *
 * OpenAPI spec version: 2.0.0-Beta-1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The reference type codes defined by DCSA. - FF (Freight Forwarder’s Reference) - SI (Shipper’s Reference) - PO (Purchase Order Reference) - CR (Customer’s Reference) - AAO (Consignee’s Reference) - ECR (Empty container release reference) - CSI (Customer shipment ID) - BPR (Booking party reference number) - BID (Booking Request ID) - EQ (Equipment Reference) - RUC (Registro Único del Contribuyente) - DUE (Declaração Única de Exportação) - CER (Canadian Export Reporting System) - AES (Automated Export System)  More details can be found on <a href=\"https://github.com/dcsaorg/DCSA-Information-Model/blob/master/datamodel/referencedata.d/referencetypes.csv\">GitHub</a>. 
 */
export type ReferenceType1 = 'FF' | 'SI' | 'PO' | 'CR' | 'AAO' | 'ECR' | 'CSI' | 'BPR' | 'BID' | 'EQ' | 'RUC' | 'DUE' | 'CER' | 'AES';

export const ReferenceType1 = {
    FF: 'FF' as ReferenceType1,
    SI: 'SI' as ReferenceType1,
    PO: 'PO' as ReferenceType1,
    CR: 'CR' as ReferenceType1,
    AAO: 'AAO' as ReferenceType1,
    ECR: 'ECR' as ReferenceType1,
    CSI: 'CSI' as ReferenceType1,
    BPR: 'BPR' as ReferenceType1,
    BID: 'BID' as ReferenceType1,
    EQ: 'EQ' as ReferenceType1,
    RUC: 'RUC' as ReferenceType1,
    DUE: 'DUE' as ReferenceType1,
    CER: 'CER' as ReferenceType1,
    AES: 'AES' as ReferenceType1
};