/**
 * DCSA OpenAPI specification for Booking v2 - Beta 1
 * API specification issued by DCSA.org.  For explanation to specific values or objects please refer to the *** [Information Model v2022.1]() *** Will be updated soon ***. This API does not define the business rules regarding what is allowed to update at what time. For this the [BKG IFS]() *** Will be updated soon *** should be consulted.  All other documents related to the Booking publication can be found [here](https://knowledge.dcsa.org/s/publication?publicationId=a0r7T000000L8mmQAC)  It is possible to use this API as a standalone API. In order to do so it is necessary to use the poll-endPoint - /v1/events  in order to poll event information.  It is recomended to implement the [DCSA Documentation Event Hub](https://app.swaggerhub.com/apis/dcsaorg/DOCUMENTATION_EVENT_HUB) in order to use the push model. Here events are pushed as they occur.  For a changelog please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/bkg/v1#v200B1). Please also [create a GitHub issue](https://github.com/dcsaorg/DCSA-OpenAPI/issues/new) if you have any questions/comments. 
 *
 * OpenAPI spec version: 2.0.0-Beta-1
 * Contact: info@dcsa.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Links to the Location Type Code defined by DCSA. - PRE (Place of Receipt) - POL (Port of Loading) - POD (Port of Discharge) - PDE (Place of Delivery) - PCF (Pre-carriage From) - PSR (Pre-carriage under shipper’s responsibility) - OIR (Onward In-land Routing) - DRL (Depot release location) - ORI (Origin of goods) - IEL (Container intermediate export stop off location) - PTP (Prohibited transshipment port) - RTP (Requested transshipment port) - FCD (Full container drop-off location) - ECP (Empty container pick-up location) 
 */
export type ShipmentLocationTypeCode = 'PRE' | 'POL' | 'POD' | 'PDE' | 'PCF' | 'PSR' | 'OIR' | 'DRL' | 'ORI' | 'IEL' | 'PTP' | 'RTP' | 'FCD' | 'ECP';

export const ShipmentLocationTypeCode = {
    PRE: 'PRE' as ShipmentLocationTypeCode,
    POL: 'POL' as ShipmentLocationTypeCode,
    POD: 'POD' as ShipmentLocationTypeCode,
    PDE: 'PDE' as ShipmentLocationTypeCode,
    PCF: 'PCF' as ShipmentLocationTypeCode,
    PSR: 'PSR' as ShipmentLocationTypeCode,
    OIR: 'OIR' as ShipmentLocationTypeCode,
    DRL: 'DRL' as ShipmentLocationTypeCode,
    ORI: 'ORI' as ShipmentLocationTypeCode,
    IEL: 'IEL' as ShipmentLocationTypeCode,
    PTP: 'PTP' as ShipmentLocationTypeCode,
    RTP: 'RTP' as ShipmentLocationTypeCode,
    FCD: 'FCD' as ShipmentLocationTypeCode,
    ECP: 'ECP' as ShipmentLocationTypeCode
};